In [1]:
import pandas as pd

In [36]:
df_mindful = pd.read_csv("wayid2weights_mindful.csv")
df_vibrant = pd.read_csv("wayid2weights_vibrant.csv")

# df_mindful = df_mindful.rename(columns = {
#     "environment":"environment_mindful",
#     "support":"support_mindful",
#     "safety":"safety_mindful",
# })

# df_vibrant = df_vibrant.rename(columns = {
#     "environment":"environment_vibrant",
#     "support":"support_vibrant",
#     "safety":"safety_vibrant",
# })

In [37]:
df_mindful.head()

       wayid        lat       lon  numpics  environment   support    safety
0   50149963  51.503563 -0.119305   131032     0.594617  0.819791  0.470506
1   39093506  51.506645 -0.127307   107570     0.510304  0.380889  0.376884
2   98477125  51.506116 -0.126964   103943     0.511229  0.393047  0.376884
3  300869142  51.506046 -0.127061   103714     0.512048  0.393047  0.376884
4  230505803  51.506046 -0.127061   102059     0.514975  0.380659  0.478475

In [38]:
df_vibrant.head()

       wayid        lat       lon  numpics  environment   support    safety
0   50149963  51.503563 -0.119305   131032     0.619842  0.876253  0.470506
1   39093506  51.506645 -0.127307   107570     0.520761  0.404201  0.376884
2   98477125  51.506116 -0.126964   103943     0.521941  0.438985  0.376884
3  300869142  51.506046 -0.127061   103714     0.522877  0.438985  0.376884
4  230505803  51.506046 -0.127061   102059     0.526303  0.419026  0.478475

In [39]:
df_mindful = df_mindful.set_index("wayid")
df_vibrant = df_vibrant.set_index("wayid")

In [44]:
df = df_mindful.join(df_vibrant, lsuffix="_mindful", rsuffix="_vibrant")
df.rename(columns={"numpics_mindful":"numpics"}, inplace=True)
df = df[["numpics","environment_mindful","support_mindful","safety_mindful",
         "environment_vibrant","support_vibrant","safety_vibrant"]]
df.head()

,numpics,environment_mindful,support_mindful,safety_mindful,environment_vibrant,support_vibrant,safety_vibrant
wayid,,,,,,,
50149963,131032,0.594617,0.819791,0.470506,0.619842,0.876253,0.470506
39093506,107570,0.510304,0.380889,0.376884,0.520761,0.404201,0.376884
98477125,103943,0.511229,0.393047,0.376884,0.521941,0.438985,0.376884
300869142,103714,0.512048,0.393047,0.376884,0.522877,0.438985,0.376884
230505803,102059,0.514975,0.380659,0.478475,0.526303,0.419026,0.478475

In [45]:
df.to_csv("wayid2weights.csv")